name: tracking_sdk
description: A lightweight tracking SDK for Flutter using Firebase Analytics.
version: 0.1.1

homepage: https://github.com/jaumpelicon/tracking-sdk
repository: https://github.com/jaumpelicon/tracking-sdk
issue_tracker: https://github.com/jaumpelicon/tracking-sdk/issues
documentation: https://github.com/jaumpelicon/tracking-sdk#readme

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
